// <auto-generated />
using System;
using LSRPO.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LSRPO.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220412135709_GroupsSeed")]
    partial class GroupsSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.AUTH_ROLE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.AUTH_USER", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("IMAGE_URL")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("USR_DESC")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("USR_FULLNAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("USR_REG_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NG_NP", b =>
                {
                    b.Property<int>("NGNP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NGNP_ID"), 1L, 1);

                    b.Property<int>("NG_ID")
                        .HasColumnType("int");

                    b.Property<int>("NO_ID")
                        .HasColumnType("int");

                    b.HasKey("NGNP_ID");

                    b.HasIndex("NG_ID");

                    b.HasIndex("NO_ID");

                    b.ToTable("NG_NP");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NG_USR", b =>
                {
                    b.Property<int>("NG_USR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NG_USR_ID"), 1L, 1);

                    b.Property<int?>("NG_ID")
                        .HasColumnType("int");

                    b.Property<int?>("USR_ID")
                        .HasColumnType("int");

                    b.HasKey("NG_USR_ID");

                    b.HasIndex("NG_ID");

                    b.HasIndex("USR_ID");

                    b.ToTable("NG_USR");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NO_TYPE", b =>
                {
                    b.Property<byte>("NO_TYPE_ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("NO_TYPE_DESCRIPTION")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("NO_TYPE_ID");

                    b.ToTable("NO_TYPES");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_PROCES_STATE", b =>
                {
                    b.Property<byte>("ST_ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("ST_DESC")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ST_ID");

                    b.ToTable("NOT_PROCES_STATES");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_PROCESS", b =>
                {
                    b.Property<int>("NPR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NPR_ID"), 1L, 1);

                    b.Property<int?>("NG_ID")
                        .HasColumnType("int");

                    b.Property<string>("NPR_CALL_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NPR_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NPR_END_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("NPR_FLAG")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("NPR_HORN_ID")
                        .HasColumnType("bit");

                    b.Property<int?>("NTP_ID")
                        .HasColumnType("int");

                    b.Property<string>("PULT_NUMBER")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("USR_ID")
                        .HasColumnType("int");

                    b.HasKey("NPR_ID");

                    b.HasIndex("NTP_ID");

                    b.ToTable("NOT_PROCESS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_PULT", b =>
                {
                    b.Property<int>("PULT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PULT_ID"), 1L, 1);

                    b.Property<string>("PULT_DESCR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PULT_IP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PULT_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PULT_NUMBER")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PULT_ID");

                    b.ToTable("NOT_PULTS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_STATUS", b =>
                {
                    b.Property<int>("STAT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STAT_ID"), 1L, 1);

                    b.Property<int?>("NO_ID")
                        .HasColumnType("int");

                    b.Property<byte?>("NO_TYPE")
                        .HasColumnType("tinyint");

                    b.Property<int?>("NPR_ID")
                        .HasColumnType("int");

                    b.Property<string>("STAT_CALL_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte?>("STAT_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_GET_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_INT_COUNT")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_INT_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<string>("STAT_INT_PHONE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte?>("STAT_IN_CALL")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_MOB_COUNT")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_MOB_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<string>("STAT_MOB_PHONE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte?>("STAT_NOTIFICATION")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_NUM_OF_CALLS")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_PH1_COUNT")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_PH1_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_PH2_COUNT")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("STAT_PH2_FLAG")
                        .HasColumnType("tinyint");

                    b.Property<string>("STAT_PHONE1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("STAT_PHONE2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("STAT_ID");

                    b.HasIndex("NO_ID");

                    b.HasIndex("NPR_ID");

                    b.ToTable("NOT_STATUS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_STATUS_PHONE_STATE", b =>
                {
                    b.Property<byte>("ST_ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("ST_DESC")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ST_ID");

                    b.ToTable("NOT_STATUS_PHONE_STATES");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_STATUS_STATE", b =>
                {
                    b.Property<byte>("ST_ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("ST_DESC")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ST_ID");

                    b.ToTable("NOT_STATUS_STATES");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_USER_PIN", b =>
                {
                    b.Property<int>("NOT_USR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NOT_USR_ID"), 1L, 1);

                    b.Property<int?>("USR_ID")
                        .HasColumnType("int");

                    b.Property<string>("USR_PIN")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("NOT_USR_ID");

                    b.HasIndex("USR_ID")
                        .IsUnique()
                        .HasFilter("[USR_ID] IS NOT NULL");

                    b.HasIndex("USR_PIN")
                        .IsUnique()
                        .HasFilter("[USR_PIN] IS NOT NULL");

                    b.ToTable("NOT_USERS_PIN");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOTIFY_GROUP", b =>
                {
                    b.Property<int>("NG_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NG_ID"), 1L, 1);

                    b.Property<string>("NG_DESCRIPTION")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool?>("NG_MOD_FLAG")
                        .HasColumnType("bit");

                    b.Property<string>("NG_NAME")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NG_NUMBER")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NG_REG_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("NG_ID");

                    b.ToTable("NOTIFY_GROUPS");

                    b.HasData(
                        new
                        {
                            NG_ID = 1,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПНяПНяПНяПН ",
                            NG_MOD_FLAG = false,
                            NG_NAME = "яПНяПНяПНяПН яПНяПНяПН",
                            NG_NUMBER = "8811"
                        },
                        new
                        {
                            NG_ID = 2,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПНяПНяПНяПН яПНяПНяПН + 12яПНяПН. яПНяПНяПНяПН",
                            NG_MOD_FLAG = false,
                            NG_NAME = "12яПНяПН.  яПНяПНяПН",
                            NG_NUMBER = "8812"
                        },
                        new
                        {
                            NG_ID = 3,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 3",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group3",
                            NG_NUMBER = "8813"
                        },
                        new
                        {
                            NG_ID = 4,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 4",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group4",
                            NG_NUMBER = "8814"
                        },
                        new
                        {
                            NG_ID = 5,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 5",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group5",
                            NG_NUMBER = "8815"
                        },
                        new
                        {
                            NG_ID = 6,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 6",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group6",
                            NG_NUMBER = "8816"
                        },
                        new
                        {
                            NG_ID = 7,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 7",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group7",
                            NG_NUMBER = "8817"
                        },
                        new
                        {
                            NG_ID = 8,
                            NG_DESCRIPTION = "яПНяПН. яПНяПНяПНяПНяПНяПНяПНяПН",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group8",
                            NG_NUMBER = "8818"
                        },
                        new
                        {
                            NG_ID = 9,
                            NG_DESCRIPTION = "яПНяПН. яПНяПНяПНяПНяПНяПНяПНяПН + яПНяПНяПН. яПНяПНяПНяПНяПНяПНяПНяПН",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group9",
                            NG_NUMBER = "8819"
                        },
                        new
                        {
                            NG_ID = 10,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 10",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group10",
                            NG_NUMBER = "8820"
                        },
                        new
                        {
                            NG_ID = 11,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 11",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group11",
                            NG_NUMBER = "8821"
                        },
                        new
                        {
                            NG_ID = 12,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 12",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group12",
                            NG_NUMBER = "8822"
                        },
                        new
                        {
                            NG_ID = 13,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 13",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group13",
                            NG_NUMBER = "8823"
                        },
                        new
                        {
                            NG_ID = 14,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПНяПН 2",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group14",
                            NG_NUMBER = "8824"
                        },
                        new
                        {
                            NG_ID = 15,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 15",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group15",
                            NG_NUMBER = "8825"
                        },
                        new
                        {
                            NG_ID = 16,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 16",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group16",
                            NG_NUMBER = "8826"
                        },
                        new
                        {
                            NG_ID = 17,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 17",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group17",
                            NG_NUMBER = "8827"
                        },
                        new
                        {
                            NG_ID = 18,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 18",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group18",
                            NG_NUMBER = "8828"
                        },
                        new
                        {
                            NG_ID = 19,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 19",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group19",
                            NG_NUMBER = "8829"
                        },
                        new
                        {
                            NG_ID = 20,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 20",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group20",
                            NG_NUMBER = "8830"
                        },
                        new
                        {
                            NG_ID = 21,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 21",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group21",
                            NG_NUMBER = "8831"
                        },
                        new
                        {
                            NG_ID = 22,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 22",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group22",
                            NG_NUMBER = "8832"
                        },
                        new
                        {
                            NG_ID = 23,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 23",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group23",
                            NG_NUMBER = "8833"
                        },
                        new
                        {
                            NG_ID = 24,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 24",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group24",
                            NG_NUMBER = "8834"
                        },
                        new
                        {
                            NG_ID = 25,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 25",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group25",
                            NG_NUMBER = "8835"
                        },
                        new
                        {
                            NG_ID = 26,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 26",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group26",
                            NG_NUMBER = "8836"
                        },
                        new
                        {
                            NG_ID = 27,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 27",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group27",
                            NG_NUMBER = "8837"
                        },
                        new
                        {
                            NG_ID = 28,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 28",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group28",
                            NG_NUMBER = "8838"
                        },
                        new
                        {
                            NG_ID = 29,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 29",
                            NG_MOD_FLAG = true,
                            NG_NAME = "Group29",
                            NG_NUMBER = "8839"
                        },
                        new
                        {
                            NG_ID = 30,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 30",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group30",
                            NG_NUMBER = "8840"
                        },
                        new
                        {
                            NG_ID = 31,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 31",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group31",
                            NG_NUMBER = "8841"
                        },
                        new
                        {
                            NG_ID = 32,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 32",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group32",
                            NG_NUMBER = "8842"
                        },
                        new
                        {
                            NG_ID = 33,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 33",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group33",
                            NG_NUMBER = "8843"
                        },
                        new
                        {
                            NG_ID = 34,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 34",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group34",
                            NG_NUMBER = "8844"
                        },
                        new
                        {
                            NG_ID = 35,
                            NG_DESCRIPTION = "яПНяПН. яПНяПНяПНяПНяПН",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group35",
                            NG_NUMBER = "8845"
                        },
                        new
                        {
                            NG_ID = 36,
                            NG_DESCRIPTION = "яПНяПН. яПНяПНяПНяПНяПН + яПНяПНяПН. яПНяПНяПНяПНяПН",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group36",
                            NG_NUMBER = "8846"
                        },
                        new
                        {
                            NG_ID = 37,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 37",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group37",
                            NG_NUMBER = "8847"
                        },
                        new
                        {
                            NG_ID = 38,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 38",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group38",
                            NG_NUMBER = "8848"
                        },
                        new
                        {
                            NG_ID = 39,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 39",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group39",
                            NG_NUMBER = "8849"
                        },
                        new
                        {
                            NG_ID = 40,
                            NG_DESCRIPTION = "яПНяПНяПНяПНяПН 40",
                            NG_MOD_FLAG = false,
                            NG_NAME = "Group40",
                            NG_NUMBER = "8850"
                        });
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOTIFY_OBJECT", b =>
                {
                    b.Property<int>("NO_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NO_ID"), 1L, 1);

                    b.Property<string>("NO_INT_PHONE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NO_NAME")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte?>("NO_TYPE")
                        .HasColumnType("tinyint");

                    b.Property<string>("NP_EXT_PHONE1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NP_EXT_PHONE2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NP_MOB_PHONE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PULT_ID")
                        .HasColumnType("int");

                    b.HasKey("NO_ID");

                    b.HasIndex("PULT_ID");

                    b.ToTable("NOTIFY_OBJECTS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NPR_TYPE", b =>
                {
                    b.Property<int>("NTP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NTP_ID"), 1L, 1);

                    b.Property<string>("NTP_DESCRIPTION")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NTP_ID");

                    b.ToTable("NPR_TYPES");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.STATUS_STATE", b =>
                {
                    b.Property<byte>("ST_ID")
                        .HasColumnType("tinyint");

                    b.Property<string>("ST_DESC")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ST_ID");

                    b.ToTable("STATUS_STATES");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NG_NP", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.NOTIFY_GROUP", "NOTIFY_GROUP")
                        .WithMany("NG_NPS")
                        .HasForeignKey("NG_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LSRPO.Infrastructure.Data.Models.NOTIFY_OBJECT", "NOTIFY_OBJECT")
                        .WithMany("NG_NPS")
                        .HasForeignKey("NO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NOTIFY_GROUP");

                    b.Navigation("NOTIFY_OBJECT");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NG_USR", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.NOTIFY_GROUP", "NOTIFY_GROUP")
                        .WithMany("NG_USRS")
                        .HasForeignKey("NG_ID");

                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_USER", "AUTH_USER")
                        .WithMany("NG_USRS")
                        .HasForeignKey("USR_ID");

                    b.Navigation("AUTH_USER");

                    b.Navigation("NOTIFY_GROUP");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_PROCESS", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.NPR_TYPE", "NPR_TYPE")
                        .WithMany("NOT_PROCESS")
                        .HasForeignKey("NTP_ID");

                    b.Navigation("NPR_TYPE");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_STATUS", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.NOTIFY_OBJECT", "NOTIFY_OBJECT")
                        .WithMany("NOT_STATUS")
                        .HasForeignKey("NO_ID");

                    b.HasOne("LSRPO.Infrastructure.Data.Models.NOT_PROCESS", "NOT_PROCESS")
                        .WithMany("NOT_STATUS")
                        .HasForeignKey("NPR_ID");

                    b.Navigation("NOTIFY_OBJECT");

                    b.Navigation("NOT_PROCESS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_USER_PIN", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_USER", "AUTH_USER")
                        .WithOne("NOT_USER_PIN")
                        .HasForeignKey("LSRPO.Infrastructure.Data.Models.NOT_USER_PIN", "USR_ID");

                    b.Navigation("AUTH_USER");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOTIFY_OBJECT", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.NOT_PULT", "NOT_PULT")
                        .WithMany("NOTIFY_OBJECTS")
                        .HasForeignKey("PULT_ID");

                    b.Navigation("NOT_PULT");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_ROLE", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_USER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_USER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_ROLE", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_USER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LSRPO.Infrastructure.Data.Models.AUTH_USER", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.AUTH_USER", b =>
                {
                    b.Navigation("NG_USRS");

                    b.Navigation("NOT_USER_PIN")
                        .IsRequired();
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_PROCESS", b =>
                {
                    b.Navigation("NOT_STATUS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOT_PULT", b =>
                {
                    b.Navigation("NOTIFY_OBJECTS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOTIFY_GROUP", b =>
                {
                    b.Navigation("NG_NPS");

                    b.Navigation("NG_USRS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NOTIFY_OBJECT", b =>
                {
                    b.Navigation("NG_NPS");

                    b.Navigation("NOT_STATUS");
                });

            modelBuilder.Entity("LSRPO.Infrastructure.Data.Models.NPR_TYPE", b =>
                {
                    b.Navigation("NOT_PROCESS");
                });
#pragma warning restore 612, 618
        }
    }
}
